### ISSUE TITLE
Modifying init sequence

### ISSUE THREAD

**Issue by thelwyn** [adafruit/Adafruit_CircuitPython_SSD1327#12]
Hi,

Is there a way to modify the init sequence without re compiling the lib?

For example, let say I would like to change the contrast value:

b"\x81\x01\x80"  # set contrast control

Is there a way to pass another value than x80 as an argument to override it?

Not really an issue but I didn't where else to ask.
Thanks!

**Comment by tannewt** [comment]
You don't need to compile the lib. mpy files are optional optimizations for memory use when importing. You can use .py in place of it just fine. (Just make sure the mpy isn't there as well.)

**Comment by thelwyn** [comment]
I see, thank you!
