### ISSUE TITLE
The driver for the ssd1327 is not on pypi

### ISSUE THREAD

**Issue by tjim** [adafruit/Adafruit_CircuitPython_SSD1327#8]
The driver for the ssd1327 does not appear on pypi.

Driver: https://github.com/adafruit/Adafruit_CircuitPython_SSD1327

The search page: https://pypi.org/search/?q=ssd1327

**Comment by jepler** [comment]
I was not able to determine why this package is not available on pypi (#6 does not explain), and I don't have any compatible hardware to test.  If you manually copy the adafruit_ssd1327.py file into your project is it working for you?  Normally we disable uploading to pypi when we know that the code is not compatible with Blinka and can only work with CircuitPython.

**Comment by FoamyGuy** [comment]
I think this was from before `Blink_Displayio` existed so it would have not been possible at the time. It may work fine now. I don't have hardware to check either though.

**Comment by tjim** [comment]
I've only used with a CircuitPython board before, here is how I tried it on Raspberry Pi, it fails:

    pip3 install RPI.GPIO
    pip3 install adafruit-blinka
    pip3 install adafruit-blinka-displayio
    pip3 install adafruit-circuitpython-display-text
    git clone https://github.com/adafruit/Adafruit_CircuitPython_SSD1327.git
    cp Adafruit_CircuitPython_SSD1327/examples/ssd1327_simpletest.py .
    cp Adafruit_CircuitPython_SSD1327/adafruit_ssd1327.py .
    python3 ssd1327_simpletest.py

Output is:

    Traceback (most recent call last):
      File "ssd1327_simpletest.py", line 26, in <module>
	display = adafruit_ssd1327.SSD1327(display_bus, width=WIDTH, height=HEIGHT)
      File "/home/pi/adafruit_ssd1327.py", line 91, in __init__
	single_byte_bounds=True,
      File "/home/pi/.local/lib/python3.7/site-packages/displayio/display.py", line 148, in __init__
	self._initialize(init_sequence)
      File "/home/pi/.local/lib/python3.7/site-packages/displayio/display.py", line 186, in _initialize
	self._write(command, init_sequence[i + 2 : i + 2 + data_size])
      File "/home/pi/.local/lib/python3.7/site-packages/displayio/display.py", line 197, in _write
	self._bus.begin_transaction()
    AttributeError: 'I2CDisplay' object has no attribute 'begin_transaction'

**Comment by jepler** [comment]
Ah, it appears that Adafruit_Blinka_Displayio does not yet support i2c displays at all.  https://github.com/adafruit/Adafruit_Blinka_Displayio/issues/2 -- once issue 2 is addressed in that repo, it would then be useful to upload this package to pypi.  At present it appears that only FourWire (SPI) displays are supported.

**Comment by makermelissa** [comment]
Fixed by #11
